### ISSUE TITLE
Explore: Spec Summary -> FITS still points to DR10

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#114]

**Comment by raddick** [comment]
Both the "Download" link and the "DR12 Science Archive..." link still point to the DR10 SAS.

**Comment by mtaghiza** [comment]
The "DR12 Science Archive..." link is now fixed.

The "Download" link is broken because it takes the DR version from the database table "SiteConstants", and this table is has not been yet updated. Updated manually the "RELEASE" entry to "12", but but prefer to wait and have the whole BESTDR12 changed to the final production version.

**Comment by thakar** [comment]
Actually it's not just the release number that needs to be updated in
SiteConstants, also the web and data server links (URLs).

      Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
Maybe this world is another planet's hell. [Aldous Huxley]

**Comment by mtaghiza** [comment]
Edited and fixed now the web and data server links in sciserver01

**Comment by thakar** [comment]
Fixed in v1_3_0
