### ISSUE TITLE
Entering a name that cannot be resolved in Explore results in runtime error

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#128]
If I enter "draco" in the Explore Name window and click Resolve, the RA changes to "No Coord" and the right hand pane which is supposed to show details for the object shows instead a runtime error. The error is caused by the ra value being non-numeric.

**Comment by thakar** [comment]
Also please test the following object names (submitted by a user who could not find them in Explore):

Leo A
Pegasus dSph
Draco
Cassiopeia
Coma Berenices
Ursa Minor
Segue 2
Ursa Major I
Ursa Major II

**Comment by mtaghiza** [comment]
The name resolver calls Simbad web services in France.

LEO A: there is no problem in finding this object

Pegasus dSph: simbad is unable to resolve this name. If the user writes it as "Peg dSph", then simbad will find it.

draco: draco is not an object but a constellation, and simbad finds 10 different objects associated with it. 
The object that simbad thinks is more likely to be the answer is the DRACO CLUSTER, which has no defined coordinates (that's why it does not work)
The user should have written a more defined object in that constellation.

cassiopeia: same as 'draco'. simbad finds 7 objects and thinks the returns the coordinate of CAS 1, so it works.

Coma Berenices: is a constellation. Simbad returns "COMA A" coordinates, so it works.

Ursa Minor: is a constellation. Simbad returns "UMI GALAXY" coordinates, so it works. 

Segue 2: is a galaxy, and simbad resolves it with no problem.

Ursa Major I:  is a galaxy, and simbad resolves it with no problem.

Ursa Major II: simbad finds 2 objects:

	1,ACO  1132,164.6075,+56.7917
	2,NAME UMA II GALAXY,132.8750,+63.1300

	and thinks that ACO  1132 is most likely to be the answer. So simbad is giving the wrong answer here. Skyserver has no way of understanding which of the 2 objects is the correct one, unless we use natural language processing algorithms.

**Comment by thakar** [comment]
Thanks, Manu!  This is in the sciserver version of SkyServer, I presume?
Is there any reason to think the production SkyServer would behave
differently?

      Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
The world is mud-luscious and puddle-wonderful. [E.E. Cummings]

**Comment by mtaghiza** [comment]
the production skyserver has the same behavior, since its using the same tool (Resolver.aspx) to resolve the name (calling simbad as well).
I modified the skyserver version a little, so that when the object is found by simbad but it does not provide the coordinates, it will say that the coordinates are undefined.
