### ISSUE TITLE
Double (or compound) sql statements should not be allowed on SQL search form

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#32]
Test:   s_sql_search_5

Adding ";select top 10 p.objid, p.ra, p.dec from photoobj p" at the end of the default query does bring instead 2 tables (one after the other)

**Comment by thakar** [comment]
This should not be allowed - it's happening because CasJobs allows this now, but in SkyServer this is a security risk.

**Comment by capnsue** [comment]
I can't reproduce this: adding that string to the default query produces this error message for me
{"Error Code":500,"Error Type":"InternalServerError","Error Message":"Failed to execute a query: Incorrect syntax near '#select'.","LogMessageID":"f63e2559-86af-46b9-8212-50e4db85b8e5"}

That's the correct behavior -- the ; has been replaced by a # 

(this is as a non-logged-in user)

**Comment by thakar** [comment]
Try it without the ";" just tack it on separated by space or newline.

**Comment by thakar** [comment]
Also note that for HTML output it gives a runtime error rather than a meaningful error message if you separate the queries with a ";".

**Comment by capnsue** [comment]
That is true -- I have verifed that it actually DOES run both, but it only returns the results for the first one to the web browser.  If, in SSMS you run something like 
EXEC spExecuteSQL 'select top 10 * from photoobj
select top 5 * from specobj','500000'
it will return results for both queries.  
I'm not sure the best way to fix this (if we need to fix it at all) -- trying to think of a DOS scenario where a user does a legit query and then something like SELECT * FROM PhotoObj order by rowcErr (some column without an index that will take forever to sort) -- that might slow down the server for sure.

But then again what is stopping a user from NOT writing the legit query and just running the bad query?  Nothing, that's why we have the limits in place -- and since spExecuteSQL is sending the statements to SQL server as a single batch, it's not like the users get a new time limit for each statement in their query.

**Comment by thakar** [comment]
Never underestimate the ingenuity of hackers, or idiots for that matter :-)
!

But yes, it is true that a user could always submit "SELECT * FROM
PhotoObjAll" intentionally or not, and even after inserting the limit,
"SELECT TOP 500000 * FROM PhotoObjAll" (~ 1 GB of output) could stop the
server in its tracks for a while, especially is submitted repeatedly. I
think once the query starts returning output, the timeout does not cut it
short.

        Ani


--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
It always seems impossible until it's done. [Nelson Mandela]

**Comment by capnsue** [comment]
Correct me if I am wrong, but I thought the 500000 thing was included in the webservice just for testing?  If the webservice does not pass along a limit, spExecuteSQL  inserts a "top 1000"

**Comment by thakar** [comment]
Ideally, it should be a limit that is configurable at the website level.
The SkyServer website used to set both the rowlimit and timeout from a
global include file.  However, if it cannot be passed from the website to
the WS (because that would require a code change to the WS), then I suppose
it should at least be configurable at the WS level.

     Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
It always seems impossible until it's done. [Nelson Mandela]

**Comment by capnsue** [comment]
Sorry, I am wrong -- spExecSQL inserts whatever @limit was passed along (in this case 500000) if the user doesn't include a (top n).  if the user does include a (top n) then the sp makes sure it's less than 1000.  Should we make sure the @limit is 1000 for non logged in users?  Do the querys from Skyserver hit the quick queue?  500000 seems waaay too big for anon users imo

**Comment by thakar** [comment]
SkyServer sites currently support 500k rows (or at least 100k for the older
sites) and 10-minute timeouts, so if this is executed in the quick queue
and is limited to 1000 rows, that would be a big step down.

      Ani


--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
It always seems impossible until it's done. [Nelson Mandela]

**Comment by raddick** [comment]
What's the latest on fixing this security bug? This one is important.

**Comment by raddick** [comment]
This still isn't completely fixed in sciserver_v1_2_0 .

The good news is that the queries are not being submitted, so it's not a security risk.

But the behavior is not consistent.

If you include the semicolon as reported in the original issue description returns the error message:

``SQL returned the following error: Failed to execute a query: Incorrect syntax near '#'.``

If you do not include the semicolon (and thus you just have multiple select statements), it returns the even less helpful error message:

``SQL returned the following error: ``

Added an errorhandling label since this is now mainly an error handling issue.

**Comment by thakar** [comment]
There should be an error message for the second case (no semicolon
separating multiple selects), but for the first case there may not be any
fix because spExecuteSQL converts all semicolons to #s. That has always
been the error message it returns for semicolons in the query.

      Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
Maybe this world is another planet's hell. [Aldous Huxley]

**Comment by raddick** [comment]
Closing this issue since the security problem is fixed, and verified as working in sciserver_v1_2_0 .

Opened up a new issue about the error handling question.
