### ISSUE TITLE
Test script: make sure user can't execute SQL write queries

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#48]
e.g. the user should NOT EVER be able to do a "DROP DATABASE" command.

There are lots of possible Bad Things they could do.

Let's make sure that all these cases are all clearly documented in the test script.

**Comment by capnsue** [comment]
Rather than enumerating every single Bad Thing a user could do, would it be helpful to run my AuditPerms.sql script instead, checking that skyuser, webuser, and logger have the appropriate permissions (which would be -- member of db_datareader, CONNECT, EXECUTE, SELECT, SHOWPLAN, and VIEW DEFINITION only)
This has to be run from SSMS, can't run it from the Skyserver or Casjobs, obviously :)

**Comment by raddick** [comment]
Thanks, Sue!

I don't think I have permissions to run this in SSMS, and I'm not sure which machine(s) it will need to be run on. So I'm assigning it to Ani to run the scripts.

**Comment by raddick** [comment]
Ani (@thakar), any update on this? Have you run Sue's code in SSMS, and have you verified that the user can't run Evil Queries?

**Comment by raddick** [comment]
Pinging this again. Have we verified that the user can't drop databases using any SkyServer search tool? If we have, we can close this issue, but let's make sure it's really verified first.
