### ISSUE TITLE
Some columns in CSV output are enclosed in double quotes

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#57]
For some reason, certain columns in the CSV output are enclosed in double quotes even when they are numeric (e.g. ra, dec, and in the IR spec output glon, glat, etc.).

**Comment by raddick** [comment]
Is this actually a SkyServerWS problem?

**Comment by mtaghiza** [comment]
The fields queries that appear within double quotes are strings. For example, glon is queried as str(glon,9,5) to make is smaller in size and better display it. Casjobs puts by string within double quotes by default. Seems that this behavior is ok, since astronomers are more used to used to csv files where strings are parsed in this way, as opposed to using a "comma scape character" for a comma appearing inside the string in a column. 

The solution is this case is just to cast the string as a float in the query. That way there are no quotes.

**Comment by raddick** [comment]
Verified as working in sciserver_v1_2_0
