### ISSUE TITLE
Navigate is throwing error at lowest zoom level

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#63]
Enter 269.34, 61.05 in the ra,dec windows and press Search.  Then zoom out to the lowest (rightmost) zoom level.  An exception message indicating "getFrames() has failed" is displayed.

**Comment by mtaghiza** [comment]
The problem is generated in casjobs. 
In fact, the query sent to casjobs (with database context = 'sdssimgdb') that gets the images is 

SELECT img , f.a, f.b, f.c, f.d, f.e, f.f, f.node, f.incl, f.ra, f.dec, f.fieldID, dbo.fSDSS(f.fieldID) , f.run, f.camcol, f.rerun,f.field 
FROM dbo.fGetNearbyFrameEq(179.689293428354, -0.454379056007667, 926.245074885569, 12) as n 
JOIN Frame f ON f.fieldID = n.fieldID  and f.zoom =  12  and f.iflag = 1  and f.ifieldflag=1 order by f.iorder



Executing this query returns this message:


"{\"Error Code\":500,\"Error Type\":\"InternalServerError\",\"Error Message\":\"Failed to execute a query: Query results exceed memory limitations. Please revise your query to return less information, or use MyDB\",\"LogMessageID\":\"90e1792d-0e81-4a35-b2fc-742d65224c4c\"}"

Will post this problem in the casjobs repository

**Comment by thakar** [comment]
Thanks, so do we need to open a separate CasJobs issue?

      Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
Courage is not the towering oak that sees storms come and go; it is
the fragile blossom that opens in the snow. [Alice M. Swaim]

**Comment by mtaghiza** [comment]
Fixed. Mitya increased memory limit in casjobs. Will have correct behavior in next version.

**Comment by raddick** [comment]
Verified as working in sciserver_v1_2_0
