### ISSUE TITLE
Restore 5-part SDSS ID to the Explore tool

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#67]
A change requested by Alex. For the Explore tool (link to test site below):

http://scitest02.pha.jhu.edu/SkyServer/en/tools/explore/Summary.aspx

The tool used to show the 5-part SDSS ID of the object (run-rerun-camcol-field-obj). It no longer does.

Alex would like us to restore that item. He suggests putting it on the top row, next to type.

**Comment by thakar** [comment]
This used to be in the section to the right of the image, it was
discontinued when we switched to the aspx version for DR10.  I suggest we
put it back there, rather than the top, since there seems to room for one
more row next to the image.

      Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
Courage is not the towering oak that sees storms come and go; it is
the fragile blossom that opens in the snow. [Alice M. Swaim]

**Comment by thakar** [comment]
Actually no, sorry, if there is room next to the Type and SDSS Object ID at
the top, that might be the best place since these are the components of the
objID.  So Alex's suggestion is better.

    Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
Courage is not the towering oak that sees storms come and go; it is
the fragile blossom that opens in the snow. [Alice M. Swaim]

**Comment by mtaghiza** [comment]
Fixed. These modifications will appear in the next release.

**Comment by raddick** [comment]
Verified as fixed in sciserver_v1_2_0

Again, reassigned to @mtaghiza before closing so he gets credit for doing the fix.
