### ISSUE TITLE
Is our handling of (two) query outputs in XML/CSV/JSON/VOTABLE formats consistent and sensible?

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#90]
This is a question/topic for discussion. Right now, all non-HTML output formats except for FITS are displayed in the browser window just like HTML format.  So CSV, JSON, XML, VOTable are all displayed on the screen, even when there are two query outputs, one each for regular and infrared (APOGEE) queries. Does it make sense to send these outputs to the browser window rather than saving to a file? In particular, in my Chrome browser, when I right-click on the CSV output page to save to a file, it saves the web page, not the CSV output! I think we need to come up with a consistent and useful way to handle these output formats.

**Comment by mtaghiza** [comment]
It would be easy to make saving a file to be the default, instead of rendering the output in the browser (this is already done for the fits format).

I tried with firefox, and saving the page also saves the csv text with it. The users can also do a "select all" and then paste the csv in a text editor. But anyways it does not make sense to render a 500,000 rows csv on the browser (nobody is going to search objects in it by eye).

Note that all the output is directly coming from CasJobs, with the exception of the html format, in which case the file is constructed in SkyServerWS.

**Comment by thakar** [comment]
How will we handle two query outputs when we save to file - save them both
to the same file?

     Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
Maybe this world is another planet's hell. [Aldous Huxley]

**Comment by mtaghiza** [comment]
Fixed. We decided just to always have resultsets composed by only 1 table (that is, only one query is executed). Added in both Radial and Rectangular search tools the option of having either Infrared or visible type of queries. Please, test these 2 tools thoroughly.

**Comment by raddick** [comment]
Also, change label from "visible bands" to "optical"
